# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'windows-2019'

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      compgen -c | sort | uniq
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      Get-Command -CommandType Application | % { $_.Name } | Sort-Object | Get-Unique
    pwsh: true
