# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- stderr-pool2

pool: 'Release Agents'

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      .\_init.ps1
      TestStdErr
    pwsh: true
